### ISSUE TITLE
Live & wysiwyg editing

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#220]
As an editor, I want to be able to see a live preview and even have direct manipulation and editing on that preview of an Autotune project (things like the meme tool or the chloropleth map builder) so that I can build projects that simply can’t be done with a form and HTML generated on a server somewhere. 

**This is done when:**

- [x] Add new options to `autotune-config.json`:
  - `sample` true/false - Autotune should build and deploy a sample version of this blueprint
  - `sample_data` object - Autotune should build the sample using this data. Autotune will try to generate sample data based on the form definition.
  - `live_preview` true or relative URL - URL of an HTML file in the sample to be displayed alongside the form. If true, uses `index.html`.
- [x] Changes to how blueprints are synced
  - If sample is true, we need to build and deploy the blueprint
  - Autotune should try to randomly generate content for all required fields, merging in any provided `sample_data`.
  - Samples should be deployed to the media target. The deployed location should include the blueprint slug and version.
- [x] New alternative Project view
  - Is only used when the blueprint has a `live_preview` option
  - All the existing buttons, info and form is pushed to the side to allow the live preview to take up most of the screen
  - The live preview is embedded into the page via `pym.js`
  - Changes to the form are sent to the embedded preview via pym iframe events
  - On form submit, the embedded preview is asked to send data back which is then saved with the project data

**Comment by yurivictor** [comment]
:+1:

**Comment by caseymm** [comment]
Questions
- How are we going to fit everything (form, instructions, example/preview) on the page?

- [ ] design mockup of what live edit would look like in Autotune
- [ ] user test with mocked up live editing - can be very basic
- [ ] decide which blueprint to test with - if we want to do charts, it will have to be retrofitted. How much 
- [ ] enable data to be passed between Autotune and blueprint so that `autotune.json` is always current (pym)
- [ ] generate an example for each blueprint so that a sample builds when a new project is started

in blueprint changes
- [ ] figure out whether to use tabletop to pull in spreadsheet data more quickly for live editing (or possibly in general & still just bake it out on final build)
- [ ] everything needs to be in javascript
