### ISSUE TITLE
User flow changes when initiating the `save` of a project

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#226]
The current workflow when creating a new project:

1. Create project, fill in info, save. 
2. Get taken back to the Autotune dashboard. 
3. Click into project to edit again. 
4. Subsequent saves keep on you the project edit page, but take you to the top of the page.

Ideal workflow when creating a new project, based on many user tests:

1. Create a project, fill info, save. 
2. Project saves; stays in edit page. 
3. Subsequent saves keep you in the edit project page, at your current scroll position.

Done when:
- [x] Initial save of a project keeps you on the page for the project you're editing. 
- [x] Subsequent saves don't scroll you back up to the top of the page, but leave you at your current scroll position.

**Comment by caseymm** [comment]
While this does work since the slug is updated every time the form updates, really seems like this should be setting the correct view.model.url() on project save instead of having a workaround here. See models.js #51

Also, referenced in commit 3ddf832cf564ba863198dbdbe7d6bb36065713fc - tagged the wrong one by mistake.

**Comment by caseymm** [comment]
After investigating more, I think that this may actually be an ok solution. Trying to assign the slug in the model (`view.model.url()`) on the first go-round throws an error since it's trying to do a `get` request on an object that doesn't exist yet. 

Rendering the url for a new project by pairing it with the entered (and validated) slug allows us to grab the object instance that has been created in backbone, and therefore still load the page, instead of trying to `get` this object from the db, which throws an error.
