### ISSUE TITLE
Documentation: Need docs for how to contribute

### ISSUE THREAD

**Issue by kavyasukumar** [voxmedia/autotune#258]
Feedback from HHBA media party: Please provide documentation on setting up autotune for contribution.

**Comment by LomaxRx** [comment]
I had a bit of trouble getting up and running since it's not as simple as starting a rails server in /test/dummy? I ended up following your setup instructions and then, in the app's gemfile, pointing the autotune gem to my cloned directory. 
```ruby
gem autotune, :path => '/path/to/cloned/autotune'
```
This looks like it works, but do you have a better way of doing this?

**Comment by katieodowd** [comment]
@kavyasukumar Is this still a thing?

**Comment by kavyasukumar** [comment]
This is done : https://github.com/voxmedia/autotune/wiki/Hacking-on-Autotune
