### ISSUE TITLE
Figure out authentication

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#46]
Omniauth? User models?

**Comment by maclover7** [comment]
If you are trying to restrict auth to Vox Media employees only, I would go with omniauth-google_oauth2 (as done with Beacon), and then set a lock on Google Apps domain names allowed.

If you are trying to open up to everyone and need access to GitHub repos, then do GitHub OAuth2 and omniauth-github. Otherwise, I would stick with the trusty Devise.

**Comment by ryanmark** [comment]
We're using omniauth, and setup models and routes based on what we've done on our other projects. Ultimately we'll add an omniauth strategy for every application that this thing needs to integrate with, so github, google and chorus.
