### ISSUE TITLE
Don't make me write a slug

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#96]

**Comment by laurenrabaino** [comment]
**Expected behavior:**

- Slug should autopopulate based on title entered in previous field
- Slug field should remain editable in the event we want to rewrite it. 
- Slug should update if the title field is changed in pre-publish state
- Slug field should not auto update if the title field is changed in post-publish state

**Comment by ryanmark** [comment]
I think we should push the `theme` field up above the slug, and make the slug autopopulate based on the title and theme... so `sbnation-my-fancy-graphic`
